on: 
  push:
    branches:
      main
name: Deploy com push na main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Ultiliza último código
      uses: actions/checkout@v2
    
    - name: Sincroniza arquivos
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: testesitebr.bistec.com.pt/teste/