on: 
  push:
    branches:
      teste
name: Deploy com push na teste
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Ultiliza último código
      uses: actions/checkout@v2
    
    - name: Sincroniza arquivos
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_NAME }}
        password: ${{ secrets.HOST_PASSWD }}
        server-dir: public_html/outroteste/